### ISSUE TITLE
No Option to Input Differential Values

### ISSUE THREAD

**Issue by asIronSharpensIron** [Ldalvik/ForzaOpenTuneFormatter#1]
When attempting to create a tune, I don't have the ability to input differential values. This occurred both when I went through the entire form from top to bottom and when I entered my tuning first. When I entered my tuning first, I was able to enter diff values, but the option disappeared after entering the Upgrades. In both cases, the diff value didn't show up in the copy-able tune. 
Google Chrome v. 98.0.4758.102

**Comment by Ldalvik** [comment]
Hi, could you replicate this issue for me and send screenshots + the tune when copied to clipboard? You can reach me in the ForzaOpenTunes discord, my username is root.#3543

**Comment by Ldalvik** [comment]
Drivetrain swap is an input text box instead dropdown for some reason, and putting anything other than "AWD, FWD, RWD" will remove the differential section. This was easily fixed by making the drivetrain swap into a dropdown with "STOCK, AWD, FWD, RWD" as the selections. This change is going to be held off until the next update, so I won't close this issue this yet. Thanks for reporting it👍

**Comment by Ldalvik** [comment]
Input method changed to dropdown menu with a default value
